apiVersion: apps/v1
kind: Deployment
metadata:
  name: mep-deployment
  labels:
    app: mep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mep
  template:
    metadata:
      labels:
        app: mep
    spec:
      containers:
      - name: mep
        image: augustincramer1999/mise-en-production:latest
        ports:
        - containerPort: 8501