"""Defines subjects for further corpus filtering"""

technology = [
    "technology",
    "innovation",
    "computer",
    "high",
    "tech",
    "high-tech",
    "science",
    "engineering",
]

consumer_protection = [
    "privacy",
    "data",
    "leak",
    "leak",
    "fake",
    "news",
    "",
    "safety",
    "decept",
    "defective",
    "hack",
]

firms = [
    "google",
    "alphabet",
    "apple",
    "facebook",
    "meta",
    "amazon",
    "microsoft",
]


products = [
    "chrome",
    "incognito",
    "youtube",
    "nexus",
    "pixel",
    "google",
    "drive",
    "gmail",
    "glass",
    "street",
    "view",
    "buzz",
    "fitbit",
    "maps",
    "doodle",
    "play",
    "translate",
    "search",
    "google",
    "news",
    "nest",
    "hub",
    "xl",
    "nest",
    "chromecast",
    "stadia",
    "hub",
    "marshmallow",
    "lollipop",
    "cloud",
    "waymo",
    "earth",
    "engine",
    "apple",
    "pay",
    "apple",
    "watch",
    "iphone",
    "ipad",
    "ipod",
    "iwatch",
    "macbook",
    "macbook",
    "pro",
    "macbook",
    "air",
    "mac",
    "imac",
    "airpods",
    "ios",
    "siri",
    "icloud",
    "apple",
    "tv",
    "apple",
    "music",
    "app",
    "store",
    "safari",
    "x",
    "app",
    "apple",
    "store",
    "xr",
    "xs",
    "se",
    "iphones",
    "itunes",
    "ibook",
    "plus",
    "pro",
    "max",
    "mini",
    "os",
    "airtag",
    "airtags",
    "arcade",
    "homepod",
    "keynote",
    "ipados",
    "id",
    "foxconn",
    "facetime",
    "beat",
    "stalk",
    "messenger",
    "instagram",
    "whatsapp",
    "page",
    "feed",
    "oculus",
    "prime",
    "kindle",
    "publishing",
    "amazon",
    "prime",
    "amazon",
    "drive",
    "amazon",
    "video",
    "amazon",
    "business",
    "amazon",
    "web",
    "service",
    "amazon",
    "cloud",
    "alexa",
    "echo",
    "dot",
    "echo",
    "dot",
    "delivery",
    "amazon",
    "uk",
    "unlimited",
    "episode",
    "foods",
    "grocery",
    "grand",
    "tour",
    "grand",
    "tour",
    "viking",
    "vikings",
    "argo",
    "argos",
    "macmillan",
    "dvd",
    "clarkson",
    "lord",
    "ring",
    "hair",
    "skin",
    "vacuum",
    "pre",
    "beer",
    "drake",
    "spark",
    "kart",
    "dog",
    "twitch",
    "cat",
    "xo",
    "matthew",
    "stafford",
    "ratchet",
    "clank",
    "swagway",
    "album",
    "mouse",
    "showbiz",
    "beauty",
    "guardian",
    "batman",
    "arkham",
    "gc",
    "hair",
    "skin",
    "shirt",
    "lovefilm",
    "mirzapur",
    "cast",
    "audio",
    "drama",
    "movie",
    "jack",
    "ryan",
    "actor",
    "character",
    "lucifer",
    "outlander",
    "premier",
    "super",
    "mario",
    "sky",
    "channel",
    "voyage",
    "windows",
    "window",
    "xp",
    "surface",
    "xbox",
    "studio",
    "microsoft",
    "office",
    "office",
    "word",
    "cortana",
    "surface",
    "pro",
    "teams",
    "playstation",
    "microsoft",
    "edge",
    "edge",
    "gear",
    "outlook",
    "halo",
    "skype",
    "kinect",
    "internet",
    "explorer",
    "explorer",
    "ie",
    "bing",
    "xcloud",
    "hololens",
    "forza",
    "ori",
    "scarlett",
    "scorpio",
    "wordperfect",
    "valhalla",
    "onedrive",
    "games",
    "gold",
    "lumia",
    "azure",
    "assassin",
    "creed",
    "assassin",
    "creed",
    "minecraft",
    "yammer",
    "warcraft",
    "tay",
]


ceos = [
    "sundar",
    "pichai",
    "eric",
    "schmidt",
    "steve",
    "jobs",
    "tim",
    "cook",
    "mark",
    "zuckerberg",
    "andy",
    "jassy",
    "jeff",
    "bezos",
    "satya",
    "nadella",
    "bill",
    "gates",
    "gates",
    "steve",
    "job",
    "steve",
    "tim",
    "cook",
    "zuckerberg",
    "ceo",
    "tim",
    "cook",
    "",
    "steve",
    "ballmer",
    "ballmer",
    "elop",
    "schiller",
    "fadell",
    "phil",
    "spencer",
    "spencer",
    "mcspirit",
    "sandberg",
    "paul",
    "allen",
    "larry",
    "hryb",
    "hryb",
]


types = [
    "tablet",
    "mobile",
    "laptop",
    "pc",
    "computer",
    "desktop",
    "smartphone",
    "smartwatch",
    "search",
    "engine",
    "software",
    "hardware",
    "machine",
    "browser",
    "ebook",
    "book",
    "reader",
    "console",
    "headphone",
    "earbud",
    "bud",
    "store",
    "music",
    "gaming",
    "operating",
    "streaming",
    "title",
    "chatbot",
]


competitor = [
    "samsung",
    "galaxy",
    "twitter",
    "tiktok",
    "switch",
    "sony",
    "asos",
    "activision",
    "blizzard",
    "activision",
    "blizzard",
    "nintendo",
    "snes",
    "netflix",
    "android",
    "yahoo",
    "nokia",
    "huawei",
    "motorola",
    "htc",
    "blackberry",
    "oppo",
    "oneplus",
    "rim",
    "symbian",
    "bbc",
    "morrison",
    "spotify",
]


configue = [
    "device",
    "feature",
    "battery",
    "screen",
    "sound",
    "gb",
    "g",
    "k",
    "mm",
    "chip",
    "processor",
    "design",
    "display",
    "touch",
    "ram",
    "inch",
    "keyboard",
    "camera",
    "handset",
    "speaker",
    "button",
    "touchscreen",
    "storage",
    "data",
]


celebrity = [
    "dubost",
    "neymar",
    "amanda",
    "beyonce",
    "blur",
    "richard",
    "hammond",
    "ranj",
    "jeremy",
    "clarkson",
    "jeremy",
    "momoa",
    "jared",
    "aniston",
    "smith",
    "kim",
    "tony",
    "tom",
    "sophie",
    "oasis",
    "trio",
    "sharon",
    "betty",
    "raoul",
    "moat",
    "lauren",
    "andrew",
    "samuel",
    "gibbs",
    "samuel",
    "gibbs",
    "van",
    "gaal",
]

events_keywords = [
    "Digital Economy Act",
    "Digital infrastructure",
    "Broadband access",
    "Online services regulation",
    "Copyright protection",
    "E-commerce taxation",
    "Internet governance",
    "Cybersecurity measures",
    "Data privacy",
    "Electronic signatures",
    "Online content distribution",
    "Intellectual property rights",
    "Cybercrime prevention",
    "Internet service providers",
    "Digital skills development",
    "Digital inclusion",
    "Online marketplace regulation",
    "Data encryption",
    "E-government services",
    "Digital transformation",
    "Online advertising regulations",
    "Consumers Rights Act",
    "Consumer protection",
    "Product warranties",
    "Unfair commercial practices",
    "Consumer contracts",
    "Product liability",
    "Price transparency",
    "Digital content rights",
    "Consumer dispute resolution",
    "Unfair terms and conditions",
    "Product safety standards",
    "Consumer rights enforcement",
    "Distance selling regulations",
    "Consumer rights education",
    "Consumer advocacy",
    "Consumer awareness campaigns",
    "Consumer rights in e-commerce",
    "Consumer rights in services",
    "Misleading advertising",
    "Consumer redress",
    "Consumer rights advocacy",
    "Investigatory Powers Act",
    "Surveillance powers",
    "Communications data retention",
    "Interception of communications",
    "National security",
    "Privacy rights",
    "Judicial oversight",
    "Intelligence agencies",
    "Data retention policies",
    "Counter-terrorism measures",
    "Surveillance technologies",
    "Metadata collection",
    "Law enforcement access",
    "Targeted surveillance",
    "Bulk data collection",
    "Human rights implications",
    "Digital forensics",
    "Internet surveillance",
    "Data interception",
    "Communications monitoring",
    "Privacy safeguards",
    "European Withdrawal Act",
    "Brexit legislation",
    "EU withdrawal process",
    "Transition period",
    "Legal continuity",
    "Trade agreements",
    "Customs arrangements",
    "Regulatory alignment",
    "Single market access",
    "Customs union",
    "Northern Ireland protocol",
    "Immigration policies",
    "Fisheries policy",
    "Devolution implications",
    "EU law transposition",
    "Regulatory divergence",
    "Cross-border cooperation",
    "Dispute resolution mechanisms",
    "Financial settlement",
    "Citizens rights",
    "Future relationship negotiations",
    "Data Protection Act",
    "Personal data protection",
    "Data processing rights",
    "Data subject consent",
    "Data controllers",
    "Data processors",
    "Data protection officers",
    "GDPR compliance",
    "Data breaches",
    "Data security measures",
    "Privacy by design",
    "Data access requests",
    "Data portability",
    "Data retention policies",
    "Data anonymization",
    "Privacy impact assessments",
    "Data protection policies",
    "Data protection authorities",
    "Data protection training",
    "International data transfers",
    "Data protection audits",
    "Online Safety Bill",
    "Online content moderation",
    "Harmful content regulation",
    "Social media platforms",
    "Cyberbullying prevention",
    "Online harassment",
    "Online grooming prevention",
    "Age-appropriate design",
    "Reporting mechanisms",
    "Content removal policies",
    "User safety features",
    "Online platform liability",
    "Online child protection",
    "Online privacy settings",
    "Content filtering",
    "Digital citizenship education",
    "Online accountability measures",
    "Technology-assisted content moderation",
    "AI-powered content analysis",
    "Online community guidelines",
    "Online platform transparency",
    "National Data Strategy",
    "Data governance framework",
    "Data sharing agreements",
    "Data interoperability",
    "Data standards",
    "Data ethics",
    "Data quality assurance",
    "Data analytics capabilities",
    "Data infrastructure",
    "Data innovation initiatives",
    "Data-driven decision-making",
    "Open data initiatives",
    "Data privacy regulations",
    "Data stewardship",
    "Data security protocols",
    "Data empowerment",
    "Data access policies",
    "Data monetization strategies",
    "Data privacy impact assessments",
    "Data collaboration platforms",
    "Data utilization frameworks",
    "Digital Services Act",
    "Online platform regulation",
    "Intermediary liability",
    "Content removal procedures",
    "Platform transparency",
    "Digital advertising regulations",
    "User data protection",
    "Market dominance assessment",
    "Antitrust measures",
    "Consumer rights online",
    "Disinformation mitigation",
    "Online marketplace fairness",
    "Platform competition",
    "Algorithmic transparency",
    "Platform accountability",
    "Data portability",
    "Platform governance",
    "User-generated content rules",
    "Online competition policy",
    "Data access for researchers",
    "User profiling restrictions",
    "Telecommunications Bill",
    "Telecom infrastructure",
    "Broadband access",
    "Spectrum allocation",
    "Telecommunications regulation",
    "Competition in telecom industry",
    "Universal service obligations",
    "Mobile network coverage",
    "5G deployment",
    "Net neutrality",
    "Telecom licensing",
    "Consumer protection in telecom",
    "Interconnection agreements",
    "Telecom market liberalization",
    "Telecom innovation",
    "Telecom pricing regulation",
    "Emergency services access",
    "Telecom standards",
    "Telecom mergers and acquisitions",
    "Telecom regulatory authority",
    "Telecom investment incentives",
    "National Security and Investment Act",
    "Foreign direct investment",
    "National security review",
    "Critical infrastructure protection",
    "Investment screening",
    "Sensitive technologies",
    "Technology transfer regulations",
    "National security risks assessment",
    "Mergers and acquisitions scrutiny",
    "National security interests",
    "Investor due diligence",
    "Risk mitigation measures",
    "Classified information protection",
    "Technology export controls",
    "Strategic assets protection",
    "Intellectual property security",
    "Security-sensitive industries",
    "Supply chain security",
    "Export control regime",
    "Dual-use technologies",
    "Counter Terrorism Act",
    "Counter-terrorism measures",
    "Terrorism prevention",
    "Counter-terrorism strategy",
    "Anti-radicalization programs",
    "Counter-terrorism financing",
    "Intelligence sharing",
    "Counter-terrorism investigations",
    "Terrorist organizations",
    "Emergency powers",
    "Border security",
    "Surveillance of suspects",
    "Terrorist financing networks",
    "Counter-terrorism training",
    "Law enforcement cooperation",
    "Terrorism risk assessment",
    "Counter-terrorism legislation",
    "Cyberterrorism prevention",
    "Airport security measures",
    "National security agencies",
    "Terrorism deterrence",
    "Coronavirus Act",
    "Pandemic response",
    "Public health emergency",
    "Quarantine measures",
    "Contact tracing",
    "Vaccine distribution",
    "Emergency powers",
    "Healthcare capacity",
    "Medical supplies procurement",
    "Economic stimulus packages",
    "Remote work policies",
    "Education continuity measures",
    "Travel restrictions",
    "Healthcare infrastructure",
    "Mental health support",
    "Testing and diagnostics",
    "Vaccination rollout",
    "Crisis communication strategies",
    "Social distancing measures",
    "Healthcare workforce support",
    "Public awareness campaigns",
    "Brexit Referendum",
    "EU membership",
    "Referendum campaign",
    "Leave campaign",
    "Remain campaign",
    "Voter turnout",
    "Immigration debate",
    "Trade implications",
    "Sovereignty arguments",
    "Economic forecasts",
    "Negotiation process",
    "Article 50 trigger",
    "Single market access",
    "Customs union",
    "Northern Ireland border",
    "EU citizens rights",
    "Brexit impact assessments",
    "Transition period",
    "Withdrawal agreement",
    "EU-UK future relationship",
    "Brexit negotiations",
    "General Election -> Cameron / Con",
    "Conservative Party",
    "David Cameron",
    "Election campaign",
    "Coalition government",
    "Austerity policies",
    "Economic recovery",
    "Welfare reforms",
    "NHS funding",
    "Immigration policy",
    "Education reforms",
    "Foreign policy",
    "EU membership stance",
    "Housing policy",
    "Energy policy",
    "National security",
    "Taxation policies",
    "Social care reforms",
    "Small business support",
    "Defense spending",
    "Environment policies",
    "EU Referendum -> May / Con",
    "Theresa May",
    "Conservative Party",
    "Brexit negotiations",
    "EU withdrawal agreement",
    "Article 50 extension",
    "Brexit deal vote",
    "Backstop arrangement",
    "Customs union proposal",
    "Single market access",
    "Northern Ireland protocol",
    "Citizens rights",
    "Transition period",
    "No-deal Brexit preparations",
    "EU-UK future relationship",
    "Irish border issue",
    "Trade negotiations",
    "Immigration policy",
    "Financial settlement",
    "EU summit meetings",
    "General Election -> May / Con",
    "Theresa May",
    "Conservative Party",
    "Election campaign",
    "Brexit stance",
    "Coalition government",
    "Manifesto pledges",
    "Social care policy",
    "Education funding",
    "NHS funding",
    "Immigration policy",
    "Housing policy",
    "Taxation policies",
    "Defense spending",
    "Foreign policy",
    "Brexit negotiations",
    "Economic policies",
    "Small business support",
    "Energy policy",
    "Environment policies",
    "National security",
    "Brexit Fails -> Johnson / Con",
    "Boris Johnson",
    "Conservative Party",
    "Brexit negotiations",
    "Withdrawal agreement",
    "EU-UK future relationship",
    "Northern Ireland protocol",
    "Backstop arrangement",
    "Customs union proposal",
    "No-deal Brexit preparations",
    "Irish border issue",
    "Trade negotiations",
    "Immigration policy",
    "Financial settlement",
    "EU summit meetings",
    "Article 50 extension",
    "Parliament prorogation",
    "General election call",
    "Supreme Court ruling",
    "Snap election campaign",
    '"Get Brexit Done" slogan',
    "Google Tax Controversy",
    "Tax avoidance",
    "Corporate tax",
    "Multinational corporations",
    "Tax evasion",
    "Taxation policies",
    "Digital economy taxation",
    "Base erosion and profit shifting (BEPS)",
    "OECD tax guidelines",
    "Transfer pricing",
    "Double taxation agreements",
    "Tax havens",
    "Intellectual property rights",
    "Profit allocation rules",
    "Tax transparency",
    "Regulatory compliance",
    "Tax reform initiatives",
    "Cross-border taxation",
    "Corporate social responsibility",
    "Public perception of taxation",
    "Government revenue",
    "Phone Hacking Scandal",
    "News of the World",
    "Rupert Murdoch",
    "Tabloid journalism",
    "Privacy invasion",
    "Media ethics",
    "Journalistic practices",
    "Leveson Inquiry",
    "Press standards",
    "Press regulation",
    "Media ownership",
    "Public interest vs. privacy",
    "Investigative journalism",
    "Hacking techniques",
    "Whistleblower revelations",
    "Legal consequences",
    "Victim compensation",
    "Media industry reforms",
    "Journalism ethics codes",
    "Newsroom culture",
    "Media accountability",
    "Facebook Data Privacy Scandal",
    "Cambridge Analytica",
    "Mark Zuckerberg",
    "Data harvesting",
    "Data mining",
    "User privacy",
    "Data consent",
    "Third-party apps",
    "Data analytics",
    "Data protection policies",
    "GDPR compliance",
    "Regulatory investigations",
    "Data sharing practices",
    "User trust",
    "Privacy breaches",
    "Congressional hearings",
    "Public outrage",
    "Data access controls",
    "Ethical data practices",
    "Data security measures",
    "Data deletion policies",
    "Google Antitrust Investigations",
    "Antitrust laws",
    "Competition regulation",
    "Market dominance",
    "Search engine competition",
    "Online advertising market",
    "Platform monopolies",
    "Digital advertising practices",
    "Consumer choice",
    "Monopoly abuse",
    "Fair competition",
    "Regulatory scrutiny",
    "EU antitrust investigations",
    "DOJ antitrust probe",
    "Platform neutrality",
    "Competition policy reforms",
    "Market entry barriers",
    "Tech industry consolidation",
    "Market share analysis",
    "Anti-competitive behavior",
    "Pricing practices",
    "Ubers Regulatory Battles",
    "Ride-sharing industry",
    "Transportation network companies",
    "Regulatory compliance",
    "Taxi industry regulations",
    "Driver background checks",
    "Licensing requirements",
    "Gig economy workers",
    "Surge pricing",
    "Worker classification",
    "Public safety concerns",
    "Competition in transportation",
    "Ride-hailing services",
    "City-specific regulations",
    "Accessibility standards",
    "Dispute resolution mechanisms",
    "Market entry restrictions",
    "Labor rights in gig economy",
    "Consumer safety",
    "Dynamic pricing models",
    "Regulatory lobbying efforts",
    "Digital Services Tax",
    "Taxing digital businesses",
    "Taxation of tech giants",
    "Cross-border taxation",
    "International tax agreements",
    "Digital economy taxation",
    "Multinational corporations",
    "Tax avoidance measures",
    "OECD tax guidelines",
    "Profit allocation rules",
    "Tax reform initiatives",
    "Taxation policies",
    "Base erosion and profit shifting (BEPS)",
    "Double taxation agreements",
    "Tax havens",
    "Regulatory compliance",
    "Tax transparency",
    "Revenue collection methods",
    "Corporate tax rates",
    "Tax enforcement measures",
    "Public perception of taxation",
    "Data Breaches and Security Incidents",
    "Cybersecurity breaches",
    "Data security incidents",
    "Data breach notification",
    "Personal data exposure",
    "Cyberattacks",
    "Malware attacks",
    "Phishing attempts",
    "Ransomware attacks",
    "Data encryption",
    "Data protection measures",
    "Incident response plans",
    "Cybersecurity policies",
    "Data breach liability",
    "Regulatory fines",
    "Data breach investigations",
    "Identity theft prevention",
    "Customer data protection",
    "IT security protocols",
    "Cybersecurity awareness training",
    "Security breach remediation",
    "US Presidential Election",
    "Electoral process",
    "Presidential candidates",
    "Election campaign strategies",
    "Swing states",
    "Electoral college",
    "Voter turnout",
    "Campaign financing",
    "Political advertising",
    "Voter registration",
    "Election debates",
    "Polling data",
    "Election night results",
    "Electoral demographics",
    "Election interference",
    "Mail-in voting",
    "Voter suppression",
    "Transition of power",
    "Inauguration ceremony",
    "Presidential executive orders",
    "First 100 days in office",
    "Kenyan General Election",
    "Electoral process",
    "Presidential candidates",
    "Election campaign strategies",
    "Political parties",
    "Voter registration",
    "Voter turnout",
    "Election violence",
    "Electoral commission",
    "Election results",
    "Election disputes",
    "Voter education",
    "Ballot counting",
    "Election observers",
    "Campaign financing",
    "Civic engagement",
    "Constitutional issues",
    "Election monitoring",
    "Political rallies",
    "Election security",
    "Coalition politics",
    "Brazilian Presidential Election",
    "Electoral process",
    "Presidential candidates",
    "Election campaign strategies",
    "Political parties",
    "Voter registration",
    "Voter turnout",
    "Election violence",
    "Electoral commission",
    "Election results",
    "Election disputes",
    "Voter education",
    "Ballot counting",
    "Election observers",
    "Campaign financing",
    "Civic engagement",
    "Constitutional issues",
    "Election monitoring",
    "Political rallies",
    "Election security",
    "Coalition politics",
    "Indian General Elections",
    "Electoral process",
    "Prime Ministerial candidates",
    "Election campaign strategies",
    "Political parties",
    "Voter registration",
    "Voter turnout",
    "Election violence",
    "Electoral commission",
    "Election results",
    "Election disputes",
    "Voter education",
    "Ballot counting",
    "Election observers",
    "Campaign financing",
    "Civic engagement",
    "Constitutional issues",
    "Election monitoring",
    "Political rallies",
    "Election security",
    "Coalition politics",
    "Philippine Presidential Election",
    "Electoral process",
    "Presidential candidates",
    "Election campaign strategies",
    "Political parties",
    "Voter registration",
    "Voter turnout",
    "Election violence",
    "Electoral commission",
    "Election results",
    "Election disputes",
    "Voter education",
    "Ballot counting",
    "Election observers",
    "Campaign financing",
    "Civic engagement",
    "Constitutional issues",
    "Election monitoring",
    "Political rallies",
    "Election security",
    "Coalition politics",
    "Australian Federal Election",
    "Electoral process",
    "Prime Ministerial candidates",
    "Election campaign strategies",
    "Political parties",
    "Voter registration",
    "Voter turnout",
    "Election violence",
    "Electoral commission",
    "Election results",
    "Election disputes",
    "Voter education",
    "Ballot counting",
    "Election observers",
    "Campaign financing",
    "Civic engagement",
    "Constitutional issues",
    "Election monitoring",
    "Political rallies",
    "Election security",
    "Coalition politics",
    "Googles Street View Privacy Scandal",
    "Street View program",
    "Privacy invasion",
    "Data collection",
    "Facial recognition",
    "Consent for data collection",
    "Privacy laws",
    "Public surveillance",
    "Data anonymization",
    "Privacy regulations",
    "Location-based services",
    "Geospatial data",
    "Privacy settings",
    "Street-level imagery",
    "Image blurring",
    "Privacy concerns",
    "Privacy policies",
    "Data protection measures",
    "Ethical data practices",
    "User consent",
    "Facebooks Initial Public Offering (IPO)",
    "IPO launch",
    "Stock market debut",
    "Zuckerbergs shares",
    "Valuation of Facebook",
    "Underwriting banks",
    "Investment banks",
    "IPO price",
    "Market capitalization",
    "Shareholder value",
    "Publicly traded company",
    "Financial disclosure",
    "Securities and Exchange Commission (SEC)",
    "Technology IPOs",
    "Social media stocks",
    "Tech industry valuations",
    "Market volatility",
    "Tech industry trends",
    "Tech company earnings",
    "Edward Snowden Leaks",
    "NSA surveillance programs",
    "Government whistleblowers",
    "Classified information",
    "Mass surveillance",
    "PRISM program",
    "Surveillance revelations",
    "National security agencies",
    "Whistleblower protection",
    "Privacy rights",
    "Data privacy laws",
    "Whistleblower extradition",
    "Espionage charges",
    "Government transparency",
    "Public debate on surveillance",
    "International relations",
    "Digital privacy rights",
    "Civil liberties",
    "Intelligence community",
    "Government secrecy",
    "Data collection programs",
    "Apple-FBI Encryption Dispute",
    "iPhone encryption",
    "San Bernardino shooting",
    "Law enforcement access",
    "Backdoor access",
    "Data privacy vs. national security",
    "Court-ordered access",
    "Encryption standards",
    "Privacy rights",
    "Cybersecurity measures",
    "Government surveillance",
    "Legal precedent",
    "Technology companies cooperation with law enforcement",
    "Fourth Amendment rights",
    "Public safety concerns",
    "Privacy advocacy",
    "Cybersecurity debate",
    "Cambridge Analytica Scandal",
    "Data harvesting",
    "Psychological profiling",
    "Voter targeting",
    "Social media manipulation",
    "Facebook data breach",
    "Data mining",
    "Privacy violations",
    "User consent",
    "Political campaigns",
    "Electoral influence",
    "Data analytics",
    "Personalized advertising",
    "Privacy policies",
    "Regulatory investigations",
    "Ethical data practices",
    "User data protection",
    "Data privacy laws",
    "Information warfare",
    "Election interference",
    "Online propaganda",
    "WhatsApp Privacy Policy Update",
    "Data sharing policy",
    "User data consent",
    "End-to-end encryption",
    "Messaging app privacy",
    "Facebook integration",
    "User privacy concerns",
    "Data protection measures",
    "Privacy settings",
    "Regulatory scrutiny",
    "Data privacy laws",
    "Privacy policy transparency",
    "User communication security",
    "Cross-platform data sharing",
    "User trust",
    "Digital privacy rights",
    "Data security practices",
    "Personal messaging platforms",
    "Privacy advocacy",
    "Data usage policies",
    "European Court of Justices Schrems II Ruling",
    "Data transfer regulations",
    "Privacy Shield agreement",
    "Cross-border data flows",
    "Data protection laws",
    "GDPR compliance",
    "Data privacy rights",
    "Data protection authorities",
    "International data transfers",
    "Data processing agreements",
    "Data localization",
    "Privacy impact assessments",
    "Data protection safeguards",
    "Transatlantic data transfers",
    "EU-US data sharing",
    "Data protection litigation",
    "Privacy rights advocacy",
    "Data protection framework",
    "EU data protection standards",
    "Amazons Biometric Data Collection",
    "Biometric authentication",
    "Facial recognition technology",
    "Amazon Go stores",
    "Privacy concerns",
    "Data security measures",
    "Consumer consent",
    "Biometric data storage",
    "User identification",
    "Ethical data practices",
    "Data privacy regulations",
    "Surveillance technology",
    "Biometric privacy laws",
    "Consent for biometric data",
    "Retail technology",
    "User authentication methods",
    "Privacy in retail industry",
    "Biometric data usage",
    "Retail customer experience",
    "Retail industry innovation",
    "Technology in retail",
    "Chinas Social Credit System",
    "Social credit score",
    "Citizen behavior monitoring",
    "Surveillance state",
    "Government tracking",
    "Data collection",
    "Public behavior regulation",
    "Privacy concerns",
    "Algorithmic scoring",
    "Regulatory framework",
    "Ethical implications",
    "Digital surveillance",
    "Citizen trust",
    "Data privacy laws",
    "Government control",
    "Personal data protection",
    "Social credit policies",
    "Compliance monitoring",
    "Citizen rights",
    "Technology-driven governance",
    "Government accountability",
    "Elon Musk Buys Twitter",
    "Twitter acquisition",
    "Social media ownership",
    "Technology industry consolidation",
    "Elon Musks investments",
    "Tech industry trends",
    "Twitters future direction",
    "Social media innovation",
    "Technology billionaires",
    "Digital communication platforms",
    "Social media market dynamics",
    "Social media content policies",
    "Tech industry influence",
    "Online free speech",
    "User privacy concerns",
    "Monetization strategies",
    "Elon Musks impact on Twitter",
    "Platform governance",
    "Social media competition",
    "Media ownership trends",
    "Explosion of ChatGPT",
    "Natural language processing",
    "Chatbot technology",
    "OpenAIs language models",
    "AI-powered chat platforms",
    "Text generation algorithms",
    "Conversational AI",
    "GPT-3.5 architecture",
    "NLP advancements",
    "AI in customer service",
    "Virtual assistant technology",
    "Language model capabilities",
    "Ethical AI use",
    "Chatbot applications",
    "Language model training",
    "User interaction with AI",
    "AI in content creation",
    "Machine learning algorithms",
    "Conversational user experience",
    "AI for human-computer interaction",
    "AI-powered customer support",
]

new_topics = [
    "technology",
    "innovation",
    "computer",
    "high tech|high-tech",
    "science",
    "engineering",
    "privacy",
    "data leak",
    "leak",
    "fake news",
    " safety",
    "decept",
    "defective",
    "hack",
    "google",
    "alphabet",
    "apple",
    "facebook",
    "meta",
    "amazon",
    "microsoft" "chrome",
    "incognito",
    "youtube",
    "nexus",
    "pixel",
    "google drive",
    "gmail",
    "street view",
    "fitbit",
    "maps",
    "doodle",
    "translate",
    "search",
    "google news",
    "xl",
    "chromecast",
    "stadia",
    "cloud",
    "earth",
    "engine",
    "apple pay",
    "apple watch",
    "iphone",
    "ipad",
    "ipod",
    "iwatch",
    "macbook",
    "macbook pro",
    "macbook air",
    "mac",
    "imac",
    "airpods",
    "ios",
    "siri",
    "icloud",
    "apple tv",
    "apple music",
    "app store",
    "safari",
    "x",
    "app",
    "apple store",
    "xr",
    "xs",
    "se",
    "iphones",
    "itunes",
    "ibook",
    "os",
    "airtag",
    "airtags",
    "homepod",
    "keynote",
    "ipados",
    "id",
    "foxconn",
    "facetime",
    "stalk",
    "messenger",
    "instagram",
    "whatsapp",
    "page",
    "feed",
    "oculus",
    "prime",
    "kindle",
    "publishing",
    "amazon prime",
    "amazon drive",
    "amazon video",
    "amazon web service",
    "amazon cloud",
    "alexa",
    "echo dot",
    "echo",
    "dot",
    "delivery",
    "amazon uk",
    "twitch",
    "cat",
    "xo",
    "guardian",
    "audio",
    "windows",
    "window",
    "xp",
    "surface",
    "xbox",
    "studio",
    "microsoft office",
    "office",
    "word",
    "cortana",
    "surface pro",
    "teams",
    "playstation",
    "microsoft edge",
    "edge",
    "gear",
    "outlook",
    "skype",
    "kinect",
    "internet explorer",
    "explorer",
    "bing",
    "xcloud",
    "hololens",
    "forza",
    "ori",
    "scarlett",
    "scorpio",
    "wordperfect",
    "valhalla",
    "onedrive",
    "games gold",
    "lumia",
    "azure",
    "sundar",
    "pichai",
    "eric",
    "schmidt",
    "steve jobs",
    "tim cook",
    "mark zuckerberg",
    "andy jassy",
    "jeff",
    "bezos",
    "satya",
    "nadella",
    "bill gates",
    "gates",
    "steve job",
    "steve",
    "tim",
    "cook",
    "zuckerberg",
    "ceo",
    "tim cook ",
    "steve ballmer",
    "ballmer",
    "elop",
    "schiller",
    "fadell",
    "phil spencer",
    "spencer",
    "mcspirit",
    "sandberg",
    "paul",
    "allen",
    "larry hryb",
    "hryb",
    "tablet",
    "mobile",
    "laptop",
    "pc",
    "computer",
    "desktop",
    "smartphone",
    "smartwatch",
    "search engine",
    "software",
    "hardware",
    "machine",
    "browser",
    "ebook",
    "console",
    "headphone",
    "earbud",
    "store",
    "music",
    "gaming",
    "operating",
    "streaming",
    "title",
    "chatbot",
    "samsung",
    "galaxy",
    "twitter",
    "tiktok",
    "switch",
    "sony",
    "asos",
    "activision blizzard",
    "activision",
    "blizzard",
    "nintendo",
    "snes",
    "netflix",
    "android",
    "yahoo",
    "nokia",
    "huawei",
    "motorola",
    "htc",
    "blackberry",
    "oppo",
    "oneplus",
    "rim",
    "symbian",
    "bbc",
    "morrison",
    "spotify",
    "device",
    "feature",
    "battery",
    "screen",
    "sound",
    "chip",
    "processor",
    "design",
    "display",
    "touch",
    "ram",
    "inch",
    "keyboard",
    "camera",
    "handset",
    "speaker",
    "touchscreen",
    "storage",
    "data",
]
