name: ci

on:
  push:
    branches:
      - 'main'
      - 'augustin/make_modules'
      - 'augustin/make_secret_config'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: augustincramer1999/mise-en-production:latest
          build-args: |
            ENDPOINT_URL=${{ secrets.ENDPOINT_URL }}
            S3_KEY=${{ secrets.S3_KEY }}
            S3_SECRET=${{ secrets.S3_SECRET }}
            S3_TOKEN=${{ secrets.S3_TOKEN }}
